### ISSUE TITLE
Issues to solve before creating a official Wagtail PR

### ISSUE THREAD

**Issue by marteinn** [Frojd/wagtail-redirect-importer#6]
I was asked by the Wagtail core team to create a PR where we merge wagtail-redirect-importer into Wagtail, before we can do this a couple of things needs to be sorted out, this is from top of my head:

- [x] ~~Use Wagtails built in factories when constructing tests (to remove as many dependencies as possible)~~
- [x] [Fix heroku bugs "Tmp file not found on Heroku"](https://github.com/Frojd/wagtail-redirect-importer/issues/5)
- [x] [Measure code coverage and make sure we have tests for all admin actions](https://github.com/Frojd/wagtail-redirect-importer/issues/9)
- [x] [Create tests for all formats supported by tablib](https://github.com/Frojd/wagtail-redirect-importer/issues/7)
- [x] [Attribute external code better](https://github.com/Frojd/wagtail-redirect-importer/issues/8)
- [x] [Fix issue with default value for format in CLI and use a valid format choice list](https://github.com/Frojd/wagtail-redirect-importer/issues/4)
- [x] [Add support for offset and limit to handle large datasets](https://github.com/Frojd/wagtail-redirect-importer/issues/3)

Interested in helping out sorting out these issues, ping me!

**Comment by marteinn** [comment]
Regarding "Use Wagtails built in factories...", it seems I already built the project with Wagtails test suite in mind.
